//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPVideoAnalysisTools {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLink() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIPVideoAnalysisTools.ResourceLink", typeof(ResourceLink).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=https://www.bilibili.com/video/av14636033/ 的本地化字符串。
        /// </summary>
        internal static string bilibili哔哩哔哩_通用接口_ {
            get {
                return ResourceManager.GetString("bilibili哔哩哔哩(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://vip.1905.com/play/691916.shtml 的本地化字符串。
        /// </summary>
        internal static string m1095_通用接口_ {
            get {
                return ResourceManager.GetString("m1095(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://vip.yingshidaqian.com/20180806/QJ7qZHx1/index.m3u8 的本地化字符串。
        /// </summary>
        internal static string M3U8_通用接口_ {
            get {
                return ResourceManager.GetString("M3U8(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://gslb.miaopai.com/stream/ybQhjHGpgU117ZS-h5ot3A__.mp4 的本地化字符串。
        /// </summary>
        internal static string MP4_通用接口_ {
            get {
                return ResourceManager.GetString("MP4(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://v.pptv.com/show/BY5b2ECmFlS3Nbk.html 的本地化字符串。
        /// </summary>
        internal static string PPTV_通用接口_ {
            get {
                return ResourceManager.GetString("PPTV(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://www.yy.com/shenqu/play/id_1114244134692083494.html 的本地化字符串。
        /// </summary>
        internal static string YY神曲_通用接口_ {
            get {
                return ResourceManager.GetString("YY神曲(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://www.le.com/ptv/vplay/24504407.html 的本地化字符串。
        /// </summary>
        internal static string 乐视_通用接口_ {
            get {
                return ResourceManager.GetString("乐视(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://v.youku.com/v_show/id_XMzA0NDExODMyOA==.html 的本地化字符串。
        /// </summary>
        internal static string 优酷_通用接口_ {
            get {
                return ResourceManager.GetString("优酷(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://video.tudou.com/v/XMzMyNTQ1MTgwOA==.html 的本地化字符串。
        /// </summary>
        internal static string 土豆_通用接口_ {
            get {
                return ResourceManager.GetString("土豆(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://tv.sohu.com/20170428/n491121893.shtml 的本地化字符串。
        /// </summary>
        internal static string 搜狐_通用接口_ {
            get {
                return ResourceManager.GetString("搜狐(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://www.iqiyi.com/v_19rrnzk2lc.html 的本地化字符串。
        /// </summary>
        internal static string 爱奇艺_通用接口_ {
            get {
                return ResourceManager.GetString("爱奇艺(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://beaacc.com/wp.php?url=/2/sgsngq.mp4 的本地化字符串。
        /// </summary>
        internal static string 百度网盘_通用接口_ {
            get {
                return ResourceManager.GetString("百度网盘(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=https://v.qq.com/x/cover/dch07xllba4gvz8.html 的本地化字符串。
        /// </summary>
        internal static string 腾讯_vip_通用接口_ {
            get {
                return ResourceManager.GetString("腾讯_vip(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://v.qq.com/x/cover/1sfd2alytdj6njs/t0024fv0yft.html 的本地化字符串。
        /// </summary>
        internal static string 腾讯_通用接口_ {
            get {
                return ResourceManager.GetString("腾讯(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=https://www.mgtv.com/b/290856/4412865.html 的本地化字符串。
        /// </summary>
        internal static string 芒果TV_通用接口_ {
            get {
                return ResourceManager.GetString("芒果TV(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url=http://v.yinyuetai.com/video/746795 的本地化字符串。
        /// </summary>
        internal static string 音乐台_通用接口_ {
            get {
                return ResourceManager.GetString("音乐台(通用接口)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://beaacc.com/api.php?url= 的本地化字符串。
        /// </summary>
        internal static string 默认接口 {
            get {
                return ResourceManager.GetString("默认接口", resourceCulture);
            }
        }
    }
}
